#!/usr/bin/env python
# -*- coding: utf-8 -*-

import cgGraph
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("filename",
                        help="file name of cgGraph binary")
    args = parser.parse_args()

    tmap = cgGraph.load_TransitionMap(args.filename)
    print("#Node = {}".format(len(tmap.state)))
    print("#Transit = {}".format(len(tmap.transit)))
    print("#Transit/#Node = {}".format(float(len(tmap.transit)) / len(tmap.state)))
    print("#Transit/#Node^2 = {}".format(float(len(tmap.transit)) / pow(len(tmap.state), 2)))

if __name__ == '__main__':
    main()
